
export const englishToUrduDict: { [key: string]: string } = {
  "the": "یہ",
  "and": "اور",
  "or": "یا",
  "of": "کا",
  "to": "کو",
  "in": "میں",
  "for": "کے لیے",
  "with": "کے ساتھ",
  "by": "کے ذریعے",
  "from": "سے",
  "at": "پر",
  "on": "پر",
  "is": "ہے",
  "are": "ہیں",
  "was": "تھا",
  "were": "تھے",
  "be": "ہونا",
  "have": "ہے",
  "has": "ہے",
  "had": "تھا",
  "will": "گا",
  "would": "گا",
  "can": "سکتا",
  "could": "سکتا",
  "should": "چاہیے",
  "must": "ضروری",
  "may": "ہو سکتا",
  "might": "ہو سکتا",
  "do": "کرنا",
  "does": "کرتا",
  "did": "کیا",
  "done": "کیا",
  "make": "بنانا",
  "made": "بنایا",
  "get": "حاصل کرنا",
  "go": "جانا",
  "come": "آنا",
  "take": "لینا",
  "give": "دینا",
  "see": "دیکھنا",
  "know": "جاننا",
  "think": "سوچنا",
  "say": "کہنا",
  "tell": "بتانا",
  "work": "کام",
  "use": "استعمال",
  "find": "تلاش کرنا",
  "help": "مدد",
  "ask": "پوچھنا",
  "try": "کوشش کرنا",
  "feel": "محسوس کرنا",
  "look": "دیکھنا",
  "want": "چاہنا",
  "need": "ضرورت",
  "like": "پسند",
  "love": "محبت",
  "hate": "نفرت",
  
  // Technology related
  "technology": "ٹیکنالوجی",
  "computer": "کمپیوٹر",
  "internet": "انٹرنیٹ",
  "website": "ویب سائٹ",
  "software": "سافٹ ویئر",
  "application": "ایپلیکیشن",
  "program": "پروگرام",
  "code": "کوڈ",
  "development": "ترقی",
  "developer": "ڈیولپر",
  "programming": "پروگرامنگ",
  "data": "ڈیٹا",
  "database": "ڈیٹابیس",
  "system": "نظام",
  "network": "نیٹ ورک",
  "security": "سیکیورٹی",
  "mobile": "موبائل",
  "app": "ایپ",
  "digital": "ڈیجیٹل",
  "online": "آن لائن",
  "user": "صارف",
  "interface": "انٹرفیس",
  "design": "ڈیزائن",
  "framework": "فریم ورک",
  "library": "لائبریری",
  "api": "اے پی آئی",
  "server": "سرور",
  "client": "کلائنٹ",
  "browser": "براؤزر",
  "javascript": "جاوا اسکرپٹ",
  "html": "ایچ ٹی ایم ایل",
  "css": "سی ایس ایس",
  "react": "ری ایکٹ",
  "node": "نوڈ",
  "mongodb": "منگو ڈی بی",
  "supabase": "سپابیس",
  
  // Business and general
  "business": "کاروبار",
  "company": "کمپنی",
  "market": "بازار",
  "product": "پروڈکٹ",
  "service": "خدمات",
  "customer": "گاہک",
  "management": "انتظام",
  "team": "ٹیم",
  "project": "پروجیکٹ",
  "solution": "حل",
  "problem": "مسئلہ",
  "strategy": "حکمت عملی",
  "plan": "منصوبہ",
  "goal": "مقصد",
  "success": "کامیابی",
  "failure": "ناکامی",
  "growth": "ترقی",
  "innovation": "جدت",
  "quality": "معیار",
  "performance": "کارکردگی",
  "efficiency": "کارکردگی",
  "productivity": "پیداوار",
  "process": "عمل",
  "method": "طریقہ",
  "approach": "نقطہ نظر",
  "technique": "تکنیک",
  "skill": "مہارت",
  "knowledge": "علم",
  "experience": "تجربہ",
  "training": "تربیت",
  "education": "تعلیم",
  "learning": "سیکھنا",
  "research": "تحقیق",
  "analysis": "تجزیہ",
  "report": "رپورٹ",
  "study": "مطالعہ",
  "information": "معلومات",
  "content": "مواد",
  "article": "مضمون",
  "blog": "بلاگ",
  "post": "پوسٹ",
  "news": "خبریں",
  "update": "اپ ڈیٹ",
  "feature": "خصوصیت",
  "function": "فنکشن",
  "option": "آپشن",
  "choice": "انتخاب",
  "decision": "فیصلہ",
  "result": "نتیجہ",
  "outcome": "نتیجہ",
  "benefit": "فائدہ",
  "advantage": "فائدہ",
  "disadvantage": "نقصان",
  "risk": "خطرہ",
  "opportunity": "موقع",
  "challenge": "چیلنج",
  "issue": "مسئلہ",
  "concern": "فکر",
  "question": "سوال",
  "answer": "جواب",
  "response": "جواب",
  "feedback": "رائے",
  "comment": "تبصرہ",
  "opinion": "رائے",
  "view": "نظریہ",
  "idea": "خیال",
  "concept": "تصور",
  "theory": "نظریہ",
  "principle": "اصول",
  "rule": "قاعدہ",
  "law": "قانون",
  "policy": "پالیسی",
  "standard": "معیار",
  "requirement": "ضرورت",
  "specification": "تفصیلات",
  "detail": "تفصیل",
  "description": "تفصیل",
  "explanation": "وضاحت",
  "definition": "تعریف",
  "meaning": "معنی",
  "purpose": "مقصد",
  "objective": "مقصد",
  "target": "ہدف",
  "focus": "توجہ",
  "attention": "توجہ",
  "interest": "دلچسپی",
  "care": "خیال",
  "support": "مدد",
  "assistance": "مدد",
  "guidance": "رہنمائی",
  "direction": "سمت",
  "path": "راستہ",
  "way": "طریقہ",
  "manner": "انداز",
  "style": "انداز",
  "type": "قسم",
  "kind": "قسم",
  "category": "قسم",
  "group": "گروپ",
  "set": "سیٹ",
  "collection": "مجموعہ",
  "list": "فہرست",
  "item": "آئٹم",
  "element": "عنصر",
  "component": "جزو",
  "part": "حصہ",
  "section": "حصہ",
  "chapter": "باب",
  "page": "صفحہ",
  "document": "دستاویز",
  "file": "فائل",
  "folder": "فولڈر",
  "directory": "ڈائرکٹری",
  "location": "مقام",
  "place": "جگہ",
  "position": "پوزیشن",
  "area": "علاقہ",
  "region": "علاقہ",
  "zone": "زون",
  "space": "جگہ",
  "room": "کمرہ",
  "office": "دفتر",
  "building": "عمارت",
  "house": "گھر",
  "home": "گھر",
  "family": "خاندان",
  "person": "شخص",
  "people": "لوگ",
  "individual": "فرد",
  "human": "انسان",
  "man": "آدمی",
  "woman": "عورت",
  "child": "بچہ",
  "student": "طالب علم",
  "teacher": "استاد",
  "employee": "ملازم",
  "worker": "کارکن",
  "manager": "منیجر",
  "leader": "رہنما",
  "expert": "ماہر",
  "professional": "پیشہ ور",
  "specialist": "ماہر",
  "consultant": "مشیر",
  "advisor": "مشیر",
  "partner": "شریک",
  "colleague": "ساتھی",
  "friend": "دوست",
  "community": "کمیونٹی",
  "society": "معاشرہ",
  "culture": "ثقافت",
  "tradition": "روایت",
  "custom": "رسم",
  "practice": "عمل",
  "activity": "سرگرمی",
  "event": "واقعہ",
  "situation": "صورتحال",
  "condition": "حالت",
  "state": "حالت",
  "status": "حالت",
  "level": "سطح",
  "degree": "درجہ",
  "amount": "مقدار",
  "number": "نمبر",
  "count": "گنتی",
  "quantity": "مقدار",
  "size": "سائز",
  "length": "لمبائی",
  "width": "چوڑائی",
  "height": "اونچائی",
  "weight": "وزن",
  "speed": "رفتار",
  "time": "وقت",
  "date": "تاریخ",
  "day": "دن",
  "week": "ہفتہ",
  "month": "مہینہ",
  "year": "سال",
  "hour": "گھنٹہ",
  "minute": "منٹ",
  "second": "سیکنڈ",
  "moment": "لمحہ",
  "period": "مدت",
  "duration": "مدت",
  "start": "شروع",
  "begin": "شروع کرنا",
  "end": "ختم",
  "finish": "ختم کرنا",
  "complete": "مکمل",
  "continue": "جاری رکھنا",
  "stop": "رک جانا",
  "pause": "توقف",
  "break": "وقفہ",
  "rest": "آرام",
  "sleep": "نیند",
  "wake": "بیدار",
  "morning": "صبح",
  "afternoon": "دوپہر",
  "evening": "شام",
  "night": "رات",
  "today": "آج",
  "tomorrow": "کل",
  "yesterday": "کل",
  "now": "اب",
  "then": "پھر",
  "later": "بعد میں",
  "before": "پہلے",
  "after": "بعد",
  "during": "کے دوران",
  "while": "جبکہ",
  "when": "جب",
  "where": "کہاں",
  "why": "کیوں",
  "how": "کیسے",
  "what": "کیا",
  "which": "کون سا",
  "who": "کون",
  "whose": "کس کا",
  "whom": "کس کو",
  "this": "یہ",
  "that": "وہ",
  "these": "یہ",
  "those": "وہ",
  "here": "یہاں",
  "there": "وہاں",
  "everywhere": "ہر جگہ",
  "nowhere": "کہیں نہیں",
  "somewhere": "کہیں",
  "anywhere": "کہیں بھی",
  "everyone": "ہر کوئی",
  "no one": "کوئی نہیں",
  "someone": "کوئی",
  "anyone": "کوئی بھی",
  "everything": "سب کچھ",
  "nothing": "کچھ نہیں",
  "something": "کچھ",
  "anything": "کچھ بھی",
  "all": "سب",
  "none": "کوئی نہیں",
  "some": "کچھ",
  "any": "کوئی",
  "many": "بہت سے",
  "few": "کچھ",
  "several": "کئی",
  "much": "بہت",
  "little": "کم",
  "more": "زیادہ",
  "less": "کم",
  "most": "سب سے زیادہ",
  "least": "سب سے کم",
  "enough": "کافی",
  "too": "بہت",
  "very": "بہت",
  "quite": "کافی",
  "rather": "بلکہ",
  "fairly": "کافی",
  "really": "واقعی",
  "truly": "واقعی",
  "actually": "حقیقت میں",
  "certainly": "یقیناً",
  "definitely": "ضرور",
  "probably": "شاید",
  "possibly": "ممکن",
  "maybe": "شاید",
  "perhaps": "شاید",
  "surely": "یقیناً",
  "absolutely": "بالکل",
  "completely": "مکمل طور پر",
  "totally": "بالکل",
  "entirely": "مکمل طور پر",
  "fully": "مکمل طور پر",
  "partly": "جزوی طور پر",
  "mainly": "بنیادی طور پر",
  "mostly": "زیادہ تر",
  "generally": "عام طور پر",
  "usually": "عام طور پر",
  "normally": "عام طور پر",
  "typically": "عام طور پر",
  "often": "اکثر",
  "sometimes": "کبھی کبھی",
  "rarely": "شاذ و نادر",
  "never": "کبھی نہیں",
  "always": "ہمیشہ",
  "forever": "ہمیشہ",
  "again": "دوبارہ",
  "once": "ایک بار",
  "twice": "دو بار",
  "first": "پہلے",
  "third": "تیسرے",
  "last": "آخری",
  "final": "آخری",
  "next": "اگلے",
  "previous": "پچھلے",
  "following": "اگلے",
  "above": "اوپر",
  "below": "نیچے",
  "up": "اوپر",
  "down": "نیچے",
  "left": "بائیں",
  "right": "دائیں",
  "front": "سامنے",
  "back": "پیچھے",
  "inside": "اندر",
  "outside": "باہر",
  "between": "درمیان",
  "among": "میں سے",
  "around": "ارد گرد",
  "near": "قریب",
  "far": "دور",
  "close": "قریب",
  "open": "کھلا",
  "closed": "بند",
  "new": "نیا",
  "old": "پرانا",
  "young": "جوان",
  "fresh": "تازہ",
  "clean": "صاف",
  "dirty": "گندا",
  "clear": "صاف",
  "dark": "تاریک",
  "light": "روشن",
  "bright": "چمکدار",
  "beautiful": "خوبصورت",
  "ugly": "بدصورت",
  "good": "اچھا",
  "bad": "برا",
  "great": "عظیم",
  "excellent": "بہترین",
  "perfect": "کامل",
  "terrible": "خوفناک",
  "awful": "خوفناک",
  "amazing": "حیرت انگیز",
  "wonderful": "حیرت انگیز",
  "fantastic": "شاندار",
  "incredible": "ناقابل یقین",
  "impressive": "متاثر کن",
  "interesting": "دلچسپ",
  "boring": "بورنگ",
  "exciting": "پرجوش",
  "fun": "مزہ",
  "funny": "مضحکہ خیز",
  "serious": "سنجیدہ",
  "important": "اہم",
  "significant": "اہم",
  "major": "اہم",
  "minor": "معمولی",
  "main": "اہم",
  "basic": "بنیادی",
  "simple": "آسان",
  "complex": "پیچیدہ",
  "difficult": "مشکل",
  "hard": "سخت",
  "easy": "آسان",
  "soft": "نرم",
  "smooth": "ہموار",
  "rough": "کھردرا",
  "strong": "مضبوط",
  "weak": "کمزور",
  "powerful": "طاقتور",
  "heavy": "بھاری",
  "big": "بڑا",
  "large": "بڑا",
  "huge": "بہت بڑا",
  "small": "چھوٹا",
  "tiny": "چھوٹا",
  "long": "لمبا",
  "short": "چھوٹا",
  "tall": "لمبا",
  "wide": "چوڑا",
  "narrow": "تنگ",
  "thick": "موٹا",
  "thin": "پتلا",
  "full": "بھرا",
  "empty": "خالی",
  "busy": "مصروف",
  "free": "آزاد",
  "available": "دستیاب",
  "ready": "تیار",
  "finished": "ختم",
  "incomplete": "نامکمل",
  "correct": "درست",
  "wrong": "غلط",
  "true": "سچ",
  "false": "جھوٹ",
  "real": "حقیقی",
  "fake": "نقلی",
  "original": "اصلی",
  "copy": "نقل",
  "same": "یکساں",
  "different": "مختلف",
  "similar": "ملتا جلتا",
  "equal": "برابر",
  "fair": "منصفانہ",
  "unfair": "غیر منصفانہ",
  "honest": "ایماندار",
  "dishonest": "بے ایمان",
  "safe": "محفوظ",
  "dangerous": "خطرناک",
  "healthy": "صحت مند",
  "sick": "بیمار",
  "happy": "خوش",
  "sad": "اداس",
  "angry": "غصے میں",
  "upset": "پریشان",
  "worried": "فکر مند",
  "nervous": "گھبرایا",
  "calm": "پرسکون",
  "relaxed": "آرام دہ",
  "comfortable": "آرام دہ",
  "uncomfortable": "بے آرام",
  "confident": "خود اعتماد",
  "proud": "فخر",
  "ashamed": "شرمندہ",
  "embarrassed": "شرمندہ",
  "surprised": "حیران",
  "shocked": "حیران",
  "confused": "الجھن میں",
  "obvious": "واضح",
  "hidden": "چھپا",
}
